# netlify.toml  ← put this at the root of your repo
[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src  'self' https://cdn.jsdelivr.net 'unsafe-eval';
    style-src   'self' 'unsafe-inline';
    connect-src 'self' https://YOUR_PROJECT.supabase.co;
    img-src     'self' data:;
  """
