[build]
  command = "node generate-config.js && npm run --prefix webapp build"
  publish = "webapp/dist"

[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src  'self' https://cdn.jsdelivr.net 'unsafe-eval';
    style-src   'self' 'unsafe-inline';
    connect-src 'self' https://oedvfgnnheevwhpubvzf.supabase.co;
    img-src     'self' data:;
  """
