# netlify.toml  ← put this at the root of your repo
[build]
command = "npm --prefix webapp ci && npm run build --prefix webapp"
publish = "webapp/dist"

[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src  'self' https://cdn.jsdelivr.net 'unsafe-eval';
    style-src   'self' 'unsafe-inline';
    # Allow Supabase API requests; replace with your project URL for stricter CSP
    connect-src 'self' https://*.supabase.co;
    img-src     'self' data:;
  """
