name: Kalshi Full Fetch

on:
  schedule:
    - cron: "0 5 * * *"          # daily @ 05:00 UTC
  workflow_dispatch:

jobs:
  fetch-kalshi-markets:
    runs-on: ubuntu-latest
    concurrency: kalshi-full      # prevent overlapping runs

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run full fetch
        env:
          KALSHI_API_KEY:            ${{ secrets.KALSHI_API_KEY }}
          SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python kalshi_fetch.py      # ← no more “scripts/” prefix
