name: Polymarket Full Fetch

on:
  schedule:
    - cron: "0 6 * * *"     # daily at 06:00 UTC  (adjust if hourly)
  workflow_dispatch:

jobs:
  fetch-polymarket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - name: Run Polymarket fetch
        env:
          SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python polymarket_fetch.py
